#!/usr/bin/env bash
#
# Summary: Set or show the local application-specific shell version
#
# Usage: shenv local <version>
#        shenv local --unset
#
# Sets the local application-specific shell version by writing the
# version name to a file named `.shell-version'.
#
# When you run a shell command, shenv will look for a `.shell-version'
# file in the current directory and each parent directory. If no such
# file is found in the tree, shenv will use the global shell version
# specified with `shenv global'. A version specified with the
# `SHENV_VERSION' environment variable takes precedence over local
# and global versions.
#
# <version> should be a string matching a shell version known to shenv.
# The special version string `system' will use your default system shell.
# Run `shenv versions' for a list of available shell versions.

set -e
[ -n "$SHENV_DEBUG" ] && set -x

# Provide shenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec shenv-versions --bare
fi

versions=("$@")

if [ "$versions" = "--unset" ]; then
  rm -f .shell-version
elif [ -n "$versions" ]; then
  shenv-version-file-write .shell-version "${versions[@]}"
else
  if version_file="$(shenv-version-file "$PWD")"; then
    IFS=: versions=($(shenv-version-file-read "$version_file"))
    for version in "${versions[@]}"; do
      echo "$version"
    done
  else
    echo "shenv: no local version configured for this directory" >&2
    exit 1
  fi
fi
