#!/bin/bash
set -e
[ -n "$SHENV_DEBUG" ] && set -x

# Provide shenv completions
if [ "$1" = "--complete" ]; then
  exec shenv-rehash --complete
fi

shell="$(basename "${SHENV_SHELL:-$SHELL}")"

# When shenv shell integration is enabled, delegate to shenv-rehash,
# then tell the shell to empty its command lookup cache.
shenv-rehash

case "$shell" in
fish )
  # no rehash support
  ;;
* )
  echo "hash -r 2>/dev/null || true"
  ;;
esac
