#!/usr/bin/env bash
# Summary: List all shell versions that contain the given executable
# Usage: shenv whence [--path] <command>

set -e
[ -n "$SHENV_DEBUG" ] && set -x

# Provide shenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec shenv-shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  shenv-versions --bare | while read version; do
    path="$(shenv-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

SHENV_COMMAND="$1"
if [ -z "$SHENV_COMMAND" ]; then
  shenv-help --usage whence >&2
  exit 1
fi

result="$(whence "$SHENV_COMMAND")"
[ -n "$result" ] && echo "$result"
