#!/bin/bash
# Usage: shenv version-file-write <file> <version>

set -e
[ -n "$SHENV_DEBUG" ] && set -x

SHENV_VERSION_FILE="$1"
shift || true
versions=("$@")

if [ -z "$versions" ] || [ -z "$SHENV_VERSION_FILE" ]; then
  shenv-help --usage version-file-write >&2
  exit 1
fi

# Make sure the specified version is installed.
shenv-prefix "${versions[@]}" >/dev/null

# Write the version out to disk.
# Create an empty file. Using "rm" might cause a permission error.
> "$SHENV_VERSION_FILE"
for version in "${versions[@]}"; do
  echo "$version" >> "$SHENV_VERSION_FILE"
done
