#!/usr/bin/env bash
# Summary: Explain how the current shell version is set
set -e
[ -n "$SHENV_DEBUG" ] && set -x

unset SHENV_VERSION_ORIGIN

OLDIFS="$IFS"
IFS=$'\n' scripts=(`shenv-hooks version-origin`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -n "$SHENV_VERSION_ORIGIN" ]; then
  echo "$SHENV_VERSION_ORIGIN"
elif [ -n "$SHENV_VERSION" ]; then
  echo "SHENV_VERSION environment variable"
else
  shenv-version-file
fi
