#!/bin/bash
# Summary: Display prefix for a shell version
# Usage: shenv prefix [<version>]
#
# Displays the directory where a shell version is installed. If no
# version is given, `shenv prefix' displays the location of the
# currently selected version.

set -e
[ -n "$SHENV_DEBUG" ] && set -x

# Provide shenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec shenv-versions --bare
fi

if [ -n "$1" ]; then
  OLDIFS="$IFS"
  { IFS=:
    export SHENV_VERSION="$*"
  }
  IFS="$OLDIFS"
elif [ -z "$SHENV_VERSION" ]; then
  SHENV_VERSION="$(shenv-version-name)"
fi

SHENV_PREFIX_PATHS=()
OLDIFS="$IFS"
{ IFS=:
  for version in ${SHENV_VERSION}; do
    if [ "$version" = "system" ]; then
      if SHELL_PATH="$(SHENV_VERSION="${version}" shenv-which shell 2>/dev/null)"; then
        SHENV_PREFIX_PATH="${SHELL_PATH%/bin/*}"
        SHENV_PREFIX_PATH="${SHENV_PREFIX_PATH:-/}"
      else
        echo "shenv: system version not found in PATH" >&2
        exit 1
      fi
    else
      SHENV_PREFIX_PATH="${SHENV_ROOT}/versions/${version}"
    fi
    if [ -d "$SHENV_PREFIX_PATH" ]; then
      SHENV_PREFIX_PATHS=("${SHENV_PREFIX_PATHS[@]}" "$SHENV_PREFIX_PATH")
    else
      echo "shenv: version \`${version}' not installed" >&2
      exit 1
    fi
  done
}
IFS="$OLDIFS"

OLDIFS="$IFS"
{ IFS=:
  echo "${SHENV_PREFIX_PATHS[*]}"
}
IFS="$OLDIFS"
