#!/usr/bin/env bash
# Usage: shenv completions <command> [arg1 arg2...]

set -e
[ -n "$SHENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  shenv-help --usage completions >&2
  exit 1
fi

# Provide shenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec shenv-commands
fi

COMMAND_PATH="$(command -v "shenv-$COMMAND" || command -v "shenv-sh-$COMMAND")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide shenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
