#!/usr/bin/env bash

set -e
[ -n "$SHENV_DEBUG" ] && set -x

# Remove shenv-pip-rehash/libexec from PATH to avoid infinite loops in `shenv-which` (pyenv/pyenv#146)
_PATH=":${PATH}:"
_HERE="$(dirname "${BASH_SOURCE[0]}")" # remove this from PATH
_PATH="${_PATH//:${_HERE}:/:}"
_PATH="${_PATH#:}"
_PATH="${_PATH%:}"
PATH="${_PATH}"

SHENV_COMMAND_PATH="$(shenv-which "${SHENV_REHASH_REAL_COMMAND}")"
SHENV_BIN_PATH="${SHENV_COMMAND_PATH%/*}"

export PATH="${SHENV_BIN_PATH}:${PATH}"

STATUS=0
"$SHENV_COMMAND_PATH" "$@" || STATUS="$?"

# Run `shenv-rehash` after a successful installation.
if [ "$STATUS" == "0" ]; then
  shenv-rehash
fi

exit "$STATUS"
